import type { Env } from "./types";
import { AirtableClient } from "./airtable";
import { uploadAttachment, MAX_DIRECT_UPLOAD_BYTES, bytesToBase64 } from "./attachments";
import { seal, unseal } from "./crypto";
import { CORS } from "./oauth";

/**
 * The browser-side upload path.
 *
 * Tool ARGUMENTS are generated by the model one character at a time, so putting
 * file bytes in them means the model must literally type out ~1.4 MB of base64
 * per megabyte of file. That is far past any response limit, and on hosts where
 * an attached file reaches the model as extracted text rather than raw bytes it
 * is not merely slow but impossible. So bytes must never travel as tool
 * arguments.
 *
 * Instead `upload_attachment` opens an in-chat file picker and mints a sealed
 * TICKET naming the destination. The widget sends the bytes with that ticket and
 * they go straight to Airtable. The model never sees them.
 *
 * The ticket is a sealed blob like every other piece of state here — nothing is
 * written down. It carries the caller's Airtable token so the upload can be
 * performed on their behalf, is bound to ONE record + field so it cannot be
 * redirected, and expires quickly.
 */

/**
 * Two ticket kinds, deliberately sealed under DIFFERENT purposes.
 *
 * PICKER tickets back the in-chat widget. They are never shown to the model,
 * and they are the only kind `connector_upload_attachment` will open.
 *
 * LOCAL tickets are handed TO the model, for hosts like Claude Code where it can
 * read real files off disk and push them with the shell. They are accepted only
 * over HTTP. That asymmetry is the safety property: a host with no filesystem
 * (claude.ai chat) can still ask for a local ticket, but has no way to spend it
 * — it cannot run a shell, and the relay tool refuses this purpose outright. So
 * a model that cannot see a real file cannot invent one and upload it either.
 */
const PICKER_TICKET_PURPOSE = "airtable-upload-ticket";
const LOCAL_TICKET_PURPOSE = "airtable-local-upload";

export type TicketKind = "picker" | "local";
const PURPOSE: Record<TicketKind, string> = {
  picker: PICKER_TICKET_PURPOSE,
  local: LOCAL_TICKET_PURPOSE,
};

export const MAX_TICKET_TTL_SECONDS = 15 * 60;
/** Below this there is no point opening a picker — the session dies mid-choice. */
export const MIN_TICKET_TTL_SECONDS = 30;

export interface UploadTicket {
  airtableAccessToken: string;
  baseId: string;
  attachmentField: string;
  /**
   * Picker tickets pin exactly one record. Local tickets may leave this unset,
   * in which case each upload names its own record — that is what makes a whole
   * folder processable from one ticket instead of one round-trip per file.
   */
  recordId?: string;
}

/**
 * How long a ticket may live. A ticket carries a snapshot of the caller's
 * Airtable access token, so it cannot outlive that token: the picker would show
 * a session that still looks valid while Airtable has already begun rejecting
 * it. Cap the TTL at whatever the upstream token has left.
 */
export function ticketTtlSeconds(accessTokenExpiresAt: number, now = Date.now()): number {
  const remaining = Math.floor((accessTokenExpiresAt - now) / 1000);
  return Math.max(0, Math.min(MAX_TICKET_TTL_SECONDS, remaining));
}

export function mintUploadTicket(
  env: Env,
  ticket: UploadTicket,
  ttlSeconds: number,
  kind: TicketKind,
): Promise<string> {
  return seal(env.TOKEN_SEALING_KEY, PURPOSE[kind], ticket, ttlSeconds);
}

export function openUploadTicket(
  env: Env,
  token: string,
  kind: TicketKind,
): Promise<UploadTicket | null> {
  return unseal<UploadTicket>(env.TOKEN_SEALING_KEY, PURPOSE[kind], token);
}

/** Open a ticket of either kind, reporting which it was. HTTP accepts both. */
export async function openAnyUploadTicket(
  env: Env,
  token: string,
): Promise<{ ticket: UploadTicket; kind: TicketKind } | null> {
  const picker = await openUploadTicket(env, token, "picker");
  if (picker) return { ticket: picker, kind: "picker" };
  const local = await openUploadTicket(env, token, "local");
  if (local) return { ticket: local, kind: "local" };
  return null;
}

/**
 * Push bytes to Airtable using a ticket's sealed credentials and destination.
 * Shared by the direct HTTP path and the relay tool so both behave identically.
 * `recordId` overrides only where the ticket left it open.
 */
export async function uploadWithTicket(
  ticket: UploadTicket,
  file: { filename: string; contentType: string; base64: string; recordId?: string },
): Promise<unknown> {
  // A pinned ticket always wins, so a request can never redirect a picker upload.
  const recordId = ticket.recordId ?? file.recordId;
  if (!recordId) throw new Error("No record specified for this upload.");
  const client = new AirtableClient(async () => ticket.airtableAccessToken);
  return uploadAttachment(client, {
    baseId: ticket.baseId,
    recordId,
    attachmentField: ticket.attachmentField,
    filename: file.filename,
    contentType: file.contentType,
    content: file.base64,
  });
}

const OVERSIZE_MESSAGE = (bytes: number): string =>
  `That file is ${(bytes / 1048576).toFixed(1)} MB. Airtable accepts at most 5 MB through its API — ` +
  `larger files have to be added from the Airtable UI.`;

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

/**
 * POST /upload — multipart form with `file`, authorized by `ticket` (query string
 * or form field). Used by the uploader widget when the host lets its iframe reach
 * this origin directly; this is the path that supports the full 5 MB Airtable
 * allows, because it never passes through the MCP transport.
 */
export async function handleUpload(request: Request, env: Env): Promise<Response> {
  if (request.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }

  // Authenticate BEFORE touching the body. This route is public, so parsing a
  // multipart form first would let anyone make the Worker buffer a large file
  // it was always going to reject.
  //
  // The ticket travels in a HEADER, not the query string. It is a capability
  // carrying the caller's Airtable token, and URLs are the one part of a request
  // that edge, proxy and browser diagnostics routinely retain — the same reason
  // observability is disabled for this Worker. A header is equally readable
  // before the body is parsed, without that exposure.
  const rawTicket = request.headers.get("X-Upload-Ticket") || "";
  if (!rawTicket) return json({ error: "Missing upload ticket." }, 401);

  const opened = await openAnyUploadTicket(env, rawTicket);
  if (!opened) {
    return json({ error: "This upload session has expired. Ask Claude to open the uploader again." }, 401);
  }
  const ticket = opened.ticket;

  // Same reasoning for size: refuse on the declared length rather than after
  // buffering. The allowance over 5 MB covers multipart framing.
  const declared = Number(request.headers.get("Content-Length") || 0);
  if (declared > MAX_DIRECT_UPLOAD_BYTES + 1024 * 1024) {
    return json({ error: OVERSIZE_MESSAGE(declared) }, 413);
  }

  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return json({ error: "Expected a multipart form upload." }, 400);
  }

  const file = form.get("file");
  if (!(file instanceof File)) return json({ error: "No file in the request." }, 400);

  const bytes = await file.arrayBuffer();
  if (bytes.byteLength === 0) return json({ error: "That file is empty." }, 400);
  if (bytes.byteLength > MAX_DIRECT_UPLOAD_BYTES) {
    return json({ error: OVERSIZE_MESSAGE(bytes.byteLength) }, 413);
  }

  const filename = String(form.get("filename") || file.name || "upload");
  const contentType = file.type || String(form.get("contentType") || "application/octet-stream");
  // Only meaningful for an unpinned (local) ticket; uploadWithTicket ignores it
  // whenever the ticket already names a record.
  const recordId = String(form.get("recordId") || "") || undefined;
  if (!ticket.recordId && !recordId) {
    return json({ error: "This ticket is not bound to a record — send a `recordId` form field." }, 400);
  }

  try {
    const result = await uploadWithTicket(ticket, {
      filename,
      contentType,
      base64: bytesToBase64(bytes),
      recordId,
    });
    return json({ ok: true, filename, size: bytes.byteLength, recordId: ticket.recordId ?? recordId, result });
  } catch (e) {
    return json({ error: e instanceof Error ? e.message : "Upload failed." }, 502);
  }
}
