import type { Env } from "./types";
import { AirtableClient } from "./airtable";
import { uploadAttachment, MAX_DIRECT_UPLOAD_BYTES, bytesToBase64 } from "./attachments";
import { seal, unseal } from "./crypto";
import { CORS } from "./oauth";

/**
 * The browser-side upload path.
 *
 * Tool ARGUMENTS are generated by the model one character at a time, so putting
 * file bytes in them means the model must literally type out ~1.4 MB of base64
 * per megabyte of file. That is far past any response limit, and on hosts where
 * an attached file reaches the model as extracted text rather than raw bytes it
 * is not merely slow but impossible. So bytes must never travel as tool
 * arguments.
 *
 * Instead `upload_attachment` opens an in-chat file picker and mints a sealed
 * TICKET naming the destination. The widget sends the bytes with that ticket and
 * they go straight to Airtable. The model never sees them.
 *
 * The ticket is a sealed blob like every other piece of state here — nothing is
 * written down. It carries the caller's Airtable token so the upload can be
 * performed on their behalf, is bound to ONE record + field so it cannot be
 * redirected, and expires quickly.
 */

const TICKET_PURPOSE = "airtable-upload-ticket";
const TICKET_TTL_SECONDS = 15 * 60;

export interface UploadTicket {
  airtableAccessToken: string;
  baseId: string;
  recordId: string;
  attachmentField: string;
}

export function mintUploadTicket(env: Env, ticket: UploadTicket): Promise<string> {
  return seal(env.TOKEN_SEALING_KEY, TICKET_PURPOSE, ticket, TICKET_TTL_SECONDS);
}

export function openUploadTicket(env: Env, token: string): Promise<UploadTicket | null> {
  return unseal<UploadTicket>(env.TOKEN_SEALING_KEY, TICKET_PURPOSE, token);
}

/** Epoch ms at which a freshly minted ticket stops working (for display only). */
export function ticketExpiresAt(): number {
  return Date.now() + TICKET_TTL_SECONDS * 1000;
}

/**
 * Push bytes to Airtable using a ticket's sealed credentials and destination.
 * Shared by the direct HTTP path and the relay tool so both behave identically.
 */
export async function uploadWithTicket(
  ticket: UploadTicket,
  file: { filename: string; contentType: string; base64: string },
): Promise<unknown> {
  const client = new AirtableClient(async () => ticket.airtableAccessToken);
  return uploadAttachment(client, {
    baseId: ticket.baseId,
    recordId: ticket.recordId,
    attachmentField: ticket.attachmentField,
    filename: file.filename,
    contentType: file.contentType,
    content: file.base64,
  });
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...CORS },
  });
}

/**
 * POST /upload — multipart form with `file`, authorized by `ticket` (query string
 * or form field). Used by the uploader widget when the host lets its iframe reach
 * this origin directly; this is the path that supports the full 5 MB Airtable
 * allows, because it never passes through the MCP transport.
 */
export async function handleUpload(request: Request, env: Env): Promise<Response> {
  if (request.method !== "POST") {
    return json({ error: "Method not allowed" }, 405);
  }

  const url = new URL(request.url);
  let form: FormData;
  try {
    form = await request.formData();
  } catch {
    return json({ error: "Expected a multipart form upload." }, 400);
  }

  const rawTicket = url.searchParams.get("ticket") || String(form.get("ticket") || "");
  if (!rawTicket) return json({ error: "Missing upload ticket." }, 401);

  const ticket = await openUploadTicket(env, rawTicket);
  if (!ticket) {
    return json({ error: "This upload session has expired. Ask Claude to open the uploader again." }, 401);
  }

  const file = form.get("file");
  if (!(file instanceof File)) return json({ error: "No file in the request." }, 400);

  const bytes = await file.arrayBuffer();
  if (bytes.byteLength === 0) return json({ error: "That file is empty." }, 400);
  if (bytes.byteLength > MAX_DIRECT_UPLOAD_BYTES) {
    return json(
      {
        error:
          `That file is ${(bytes.byteLength / 1048576).toFixed(1)} MB. Airtable accepts at most ` +
          `5 MB through its API — larger files have to be added from the Airtable UI.`,
      },
      413,
    );
  }

  const filename = String(form.get("filename") || file.name || "upload");
  const contentType = file.type || String(form.get("contentType") || "application/octet-stream");

  try {
    const result = await uploadWithTicket(ticket, {
      filename,
      contentType,
      base64: bytesToBase64(bytes),
    });
    return json({ ok: true, filename, size: bytes.byteLength, result });
  } catch (e) {
    return json({ error: e instanceof Error ? e.message : "Upload failed." }, 502);
  }
}
