import { z } from "zod";
import { run, errorResult, type ToolRegistrar } from "./helpers";
import { downloadAttachment } from "../attachments";
import { UPLOADER_UI_URI, UPLOADER_WIDGET_HTML } from "../uploader-widget";
import {
  mintUploadTicket,
  uploadWithTicket,
  openUploadTicket,
  ticketTtlSeconds,
  MIN_TICKET_TTL_SECONDS,
} from "../upload";

export const registerAttachmentTools: ToolRegistrar = (server, ctx) => {
  const { client, env, origin } = ctx;

  // --- the uploader UI ------------------------------------------------------
  // Served as a ui:// resource the host renders in-chat. connectDomains lets the
  // iframe POST the bytes back to this Worker; where a host ignores that, the
  // widget falls back to relaying through connector_upload_attachment.
  server.registerResource(
    "uploader-ui",
    UPLOADER_UI_URI,
    {
      title: "Airtable document uploader",
      description: "In-chat file picker that sends a document straight to an Airtable attachment field.",
      mimeType: "text/html;profile=mcp-app",
      _meta: {
        ui: {
          csp: {
            connectDomains: [origin],
            resourceDomains: [origin],
          },
        },
      },
    },
    async () => ({
      contents: [
        {
          uri: UPLOADER_UI_URI,
          mimeType: "text/html;profile=mcp-app",
          text: UPLOADER_WIDGET_HTML,
        },
      ],
    }),
  );

  // --- open_upload_picker (fallback) ----------------------------------------
  // Takes only the DESTINATION. There is deliberately no parameter for file
  // content: bytes as tool arguments would have to be generated by the model,
  // which is impossibly slow for a real document and tempts it to invent a
  // substitute when it cannot see the original. The picker sends the real file.
  //
  // Deliberately NOT named "upload_attachment": models name-match "upload a
  // document" onto the closest tool name, and that must resolve to the direct
  // path wherever the file is readable. This name says what the tool really
  // does — hand the work back to the user — so it reads as the last resort it is.
  server.registerTool(
    "open_upload_picker",
    {
      title: "Ask the user to pick the document by hand (fallback)",
      description: [
        "FALLBACK ONLY: open an in-chat file picker asking the USER to select the document themselves.",
        "Use this only when you have no way to read the file — no filesystem, no shell (e.g. claude.ai",
        "web chat). If you can read the user's files, use upload_attachment instead: it needs no clicks.",
        "",
        "You CANNOT pass the file yourself — this tool takes only the destination (base, record, field).",
        "Calling it renders a picker; the user chooses the file and its exact bytes go straight to Airtable.",
        "",
        "NEVER recreate, re-type, summarize or regenerate a document in order to upload it. If you cannot",
        "read the user's original file, that is expected — the picker does not need you to. A rebuilt copy",
        "is not the user's document and must never be uploaded in its place.",
        "",
        "The record must already exist — create it first if needed. The file is APPENDED to whatever the",
        "field already holds. Airtable's API accepts at most 5 MB per file; larger files must be added",
        "from the Airtable UI.",
        "",
        "If the user gives you a public http(s) URL rather than a local file, fetch it and note that you",
        "still need this picker to place the bytes in Airtable.",
      ].join("\n"),
      inputSchema: {
        baseId: z.string().describe("Base ID, e.g. appXXXXXXXXXXXXXX"),
        recordId: z.string().describe("Existing record to attach to (rec...)"),
        attachmentField: z.string().describe("Attachment field name or ID (fld...)"),
        destinationLabel: z
          .string()
          .optional()
          .describe("Human-readable destination shown in the picker, e.g. \"Invoices - Attachments\""),
      },
      _meta: { ui: { resourceUri: UPLOADER_UI_URI } },
    },
    async ({ baseId, recordId, attachmentField, destinationLabel }) => {
      try {
        // The ticket carries a snapshot of the Airtable token, so it must not
        // outlive it — otherwise the picker advertises a live session that
        // Airtable has already started refusing.
        const ttl = ticketTtlSeconds(ctx.accessTokenExpiresAt);
        if (ttl < MIN_TICKET_TTL_SECONDS) {
          throw new Error(
            "Your Airtable session is about to expire, so an upload started now would fail part-way. " +
              "Ask again in a moment — the connector will refresh it — then upload.",
          );
        }
        const ticket = await mintUploadTicket(
          env,
          { airtableAccessToken: ctx.accessToken, baseId, recordId, attachmentField },
          ttl,
          "picker",
        );
        const expiresAt = Date.now() + ttl * 1000;
        const label = destinationLabel || `${attachmentField} on ${recordId}`;

        // The ticket is a capability: whoever holds it can push bytes to this
        // record for its lifetime. It therefore goes ONLY in `_meta`, the channel
        // the host hands to the widget. Putting it in `structuredContent` — which
        // is model-visible — would let the model call connector_upload_attachment
        // with invented `fileBase64`, recreating the very failure (a generated
        // lookalike uploaded in place of the user's file) this flow exists to
        // prevent. Model-visible output below carries no ticket.
        const widgetPayload = { uploadUrl: `${origin}/upload`, ticket, expiresAt, destinationLabel: label };
        return {
          content: [
            {
              type: "text" as const,
              text:
                "Opening the Airtable uploader — pick the document and it will be attached as-is. " +
                "Do not attempt to reproduce the file yourself. " +
                `(upload session valid until ${new Date(expiresAt).toISOString()})`,
            },
          ],
          structuredContent: { destinationLabel: label, expiresAt },
          _meta: { ui: { resourceUri: UPLOADER_UI_URI }, ...widgetPayload },
        };
      } catch (e) {
        return errorResult(e);
      }
    },
  );

  // --- connector_upload_attachment (internal) -------------------------------
  // The widget's fallback when the host's iframe CSP blocks a direct POST: it
  // hands the bytes to the host, which forwards them here, and we push them to
  // Airtable server-to-server. The destination comes from the sealed ticket, not
  // from arguments, so this cannot be aimed at another record.
  server.registerTool(
    "connector_upload_attachment",
    {
      title: "Relay a picked file to Airtable (internal)",
      description:
        "INTERNAL — invoked by the Airtable uploader widget to relay the file the user picked. " +
        "Not for direct use by the model: call open_upload_picker, which opens the picker. " +
        "Never synthesize `fileBase64` yourself.",
      inputSchema: {
        ticket: z.string().min(1).describe("Sealed upload ticket from upload_attachment."),
        filename: z.string().min(1).describe("Original filename, with extension."),
        fileBase64: z.string().min(1).describe("Base64 of the picked file (data-URI prefix tolerated)."),
        mimeType: z.string().optional().describe("MIME type, if known."),
      },
    },
    async ({ ticket, filename, fileBase64, mimeType }) => {
      try {
        // "picker" only. A local-upload ticket must never be spendable through a
        // tool call, because that is exactly the channel where the bytes would
        // have to be model-generated.
        const opened = await openUploadTicket(env, ticket, "picker");
        if (!opened) {
          throw new Error("This upload session has expired. Open the uploader again.");
        }
        const base64 = fileBase64.replace(/^data:[^;]+;base64,/, "").replace(/\s/g, "");
        const result = await uploadWithTicket(opened, {
          filename,
          contentType: mimeType || "application/octet-stream",
          base64,
        });
        return {
          content: [{ type: "text" as const, text: `Uploaded "${filename}" to Airtable.` }],
          structuredContent: { ok: true, filename, result },
        };
      } catch (e) {
        return errorResult(e);
      }
    },
  );

  // --- upload_attachment (the default) --------------------------------------
  // For hosts with a real filesystem and a shell (Claude Code). Hands back a
  // ticket the SHELL spends, so a whole folder can be processed without a picker
  // and without a single byte crossing the conversation. Carries the natural
  // name on purpose: "upload this document" must land here, not on the picker.
  server.registerTool(
    "upload_attachment",
    {
      title: "Upload documents to an Airtable attachment field (no user interaction)",
      description: [
        "THE DEFAULT WAY TO UPLOAD. Uploads one or many documents from the user's filesystem into an",
        "attachment field immediately — no clicking, no picker, no waiting on the user. Use it whenever",
        "you can read the user's files (Claude Code, desktop with folder access, any host with a shell).",
        "Do NOT open the picker just because a file was mentioned in chat — check the filesystem first.",
        "",
        "It returns an upload ticket you spend with the shell:",
        "",
        "It returns an upload URL and a ticket. Upload each file with a plain HTTP POST, e.g.:",
        '  curl -X POST "<uploadUrl>" -H "X-Upload-Ticket: <ticket>" \\',
        '       -F "file=@/path/to/report.pdf" -F "recordId=recXXXXXXXXXXXXXX"',
        "",
        "Omit `recordId` from the tool call to get one ticket that works for MANY records in the",
        "base — then pass `-F recordId=...` per file. Pass `recordId` to pin the ticket to one record.",
        "",
        "Send the real file with `-F file=@<path>`. NEVER write a file yourself and upload that, and",
        "never hand-build the request body from text you generated — upload only files that already",
        "exist on disk. The whole point of this path is that the bytes come from the user's disk",
        "rather than from you.",
        "",
        "Typical folder workflow: list the files, create_records to make one record per file, then",
        "POST each file with its recordId. Airtable caps each file at 5 MB.",
        "",
        "IF THE POST CANNOT CONNECT AT ALL — a proxy 403 on CONNECT, a DNS failure, or a refused",
        "connection rather than an HTTP response from this server — you are in a sandbox whose egress",
        "allowlist does not include this host. Do NOT silently fall back to making the user click",
        "through a picker for every file, and do NOT report that uploading is impossible. Say plainly",
        "that the sandbox is blocking network access, and give them this one-time fix for their",
        "Claude Code settings.json, which makes future runs fully unattended:",
        `  {"sandbox":{"network":{"allowedDomains":["<this server's hostname>"]}}}`,
        "Then offer the picker (open_upload_picker) as the interim route for this run.",
        "Note a 401/413/400 IS a reply from this server, so the network is fine — fix the request.",
        "",
        "The ticket is short-lived. If uploads start returning 401, call this again for a fresh one.",
      ].join("\n"),
      inputSchema: {
        baseId: z.string().describe("Base ID, e.g. appXXXXXXXXXXXXXX"),
        attachmentField: z.string().describe("Attachment field name or ID (fld...)"),
        recordId: z
          .string()
          .optional()
          .describe("Pin to one record. Omit to reuse the ticket across records in this base."),
      },
    },
    async ({ baseId, attachmentField, recordId }) => {
      try {
        const ttl = ticketTtlSeconds(ctx.accessTokenExpiresAt);
        if (ttl < MIN_TICKET_TTL_SECONDS) {
          throw new Error(
            "Your Airtable session is about to expire, so uploads started now would fail part-way. " +
              "Ask again in a moment — the connector will refresh it — then upload.",
          );
        }
        const ticket = await mintUploadTicket(
          env,
          { airtableAccessToken: ctx.accessToken, baseId, attachmentField, recordId },
          ttl,
          "local",
        );
        const uploadUrl = `${origin}/upload`;
        const expiresAt = Date.now() + ttl * 1000;
        // Named explicitly so a sandboxed caller can quote the exact allowlist
        // entry back to the user instead of guessing at it.
        let host: string;
        try {
          host = new URL(origin).hostname;
        } catch {
          host = origin;
        }
        const recordArg = recordId ? "" : ' -F "recordId=recXXXXXXXXXXXXXX"';
        return {
          content: [
            {
              type: "text" as const,
              text: [
                `Upload each file straight from disk — do not read the bytes into this conversation:`,
                "",
                `  curl -sS -X POST "${uploadUrl}" \\`,
                `       -H "X-Upload-Ticket: ${ticket}" \\`,
                `       -F "file=@/path/to/file.pdf"${recordArg}`,
                "",
                recordId
                  ? `This ticket is pinned to ${recordId}; a recordId in the request is ignored.`
                  : `Pass a recordId per file. Create the records first if they do not exist yet.`,
                `Valid until ${new Date(expiresAt).toISOString()}. Max 5 MB per file.`,
                `Upload only files that already exist on disk — never a file you generated.`,
                "",
                `If that curl cannot CONNECT (proxy 403, DNS failure, connection refused — as opposed`,
                `to an HTTP status from this server), a sandbox egress allowlist is blocking ${host}.`,
                `Tell the user, and give them this one-time settings.json fix so later runs need no`,
                `clicks: {"sandbox":{"network":{"allowedDomains":["${host}"]}}} — then use the`,
                `open_upload_picker picker for this run rather than abandoning the task.`,
              ].join("\n"),
            },
          ],
          structuredContent: { uploadUrl, ticket, expiresAt, baseId, attachmentField, recordId },
        };
      } catch (e) {
        return errorResult(e);
      }
    },
  );

  // --- download_attachment --------------------------------------------------
  server.tool(
    "download_attachment",
    [
      "Read an attachment from a record and return a fresh temporary download URL (valid ~2 hours) plus metadata (filename, size, type).",
      "In Claude Code you can fetch that URL to save the file locally (e.g. `curl -o file <url>`).",
      "Set inline:true to also receive the file bytes as base64 in the result (small files only).",
      "Select which attachment with `attachmentId` (att...), otherwise `index` is used (default 0, the first).",
    ].join("\n"),
    {
      baseId: z.string(),
      tableIdOrName: z.string(),
      recordId: z.string(),
      attachmentField: z.string().describe("Attachment field name or ID"),
      attachmentId: z.string().optional(),
      index: z.number().int().min(0).optional(),
      inline: z.boolean().optional().describe("Also return base64 bytes (small files)"),
    },
    async (a) =>
      run(() =>
        downloadAttachment(client, {
          baseId: a.baseId,
          tableIdOrName: a.tableIdOrName,
          recordId: a.recordId,
          attachmentField: a.attachmentField,
          attachmentId: a.attachmentId,
          index: a.index,
          inline: a.inline,
        }),
      ),
  );
};
